### ISSUE TITLE
issue for aaron to review my pull request

### ISSUE THREAD

**Issue by awsumpter** [thepyrodancers/Calculator#7]

**Comment by awsumpter** [comment]
Is this issue for me to review YOUR code? If so i am having trouble finding the pull request for it. Is that because you're not actually making a pull request because we're not going to be merging your fork with main? I will try to open your fork in VS and review it that way unless I hear otherwise

**Comment by awsumpter** [comment]
Also, I probably shouldn't have turned this into an actual issue lol

**Comment by davrdic** [comment]
@awsumpter i just saw your question on this. i'll try to keep an eye out for these. but yes this was so you could review my code. did you actually get to do that? for some reason i was thinking you had so i moved this to done. if you haven't, just move it back to the right column. otherwise you can close this issue.

**Comment by davrdic** [comment]
oh and i can help you find a copy of my changes if you still need help
